### ISSUE TITLE
Postgres init not working

### ISSUE THREAD

**Issue by Dreistein** [AustrianDataLAB/bakery_as_a_service#28]
I am failing to initialize the backend-db and backend using the `schema.sql`

First, there is a syntax error in the `schema.sql`.
Line 1 should contain two dashes (`--`) instead of one.

After fixing this, directus complains about some foreign constraint missing:

```
error: alter table "directus_fields" drop constraint "directus_fields_collection_foreign" - constraint "directus_fields_collection_foreign" of relation "directus_fields" does not exist
    at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 162,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '12061',
  routine: 'ATExecDropConstraint'
}
```
## Steps to reproduce
* Backup your `volumes` directory for later restoration
* `docker-compose down --volumes`
* remove the `volumes` directory
* optionally `docker-compose build`
* `docker-compose up -d`

backend-db / backend should fail

**Comment by Dreistein** [comment]
Fixed in #35
